#!/bin/bash

# Define interface width and height
NOLIN=20
NOCOL=70
NOVIW=10

setup_default()
{
  # Use scripts to setup

 # ./scripts/setup_xterm.sh
  test -f ~/dotfiles/install.sh && /bin/bash ~/dotfiles/install.sh
}


setup_audio()
{
  sudo adduser "$(whoami)" audio
}


whiptail\
  --title "Config Menu"\
  --yesno "This will configure the user and install dotfiles (if available). Are you sure?"\
  $NOLIN $NOCOL

exitstatus=$?

if [ $exitstatus = 0 ]; then
  setup_audio
  setup_default
else
  exit 0
fi




